master:
  push:
    - docker:
        image: node:22

    - name: Sync to Github
      stages:
        imports: https://cnb.cool/puresky/secret-store/-/blob/main/github.yml
        image: tencentcom/git-sync
        settings:
          target_url: https://github.com/PureSkys/sentence-collection.git
          auth_type: https
          username: ${GIT_USERNAME}
          password: ${GIT_ACCESS_TOKEN}

    - name: Build and Sync to Halo StaticServices
      stages:
        - name: Install pnpm
          script:
            - npm install -g pnpm
        - name: Install dependencies
          script:
            - pnpm install
        - name: Build
          script:
            - pnpm run generate
        - name: Deploy to Halo
          imports: https://cnb.cool/puresky/secret-store/-/blob/main/puresky.yml
          script:
            - npx halo-static-pages-deploy-cli deploy -e $ENDPOINT -i $SENTENCE_COLLECTION_ID -t $PAT -f ./.output/public