master:
  push:
    - docker:
        image: node:22
      stages:
        #          同步代码到github
        - name: sync to github
          imports: https://cnb.cool/puresky/secret-store/-/blob/main/github.yml
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/PureSkys/sentence-collection.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
        #        构建并推送文件到Halo静态项目服务目录
        - name: Install pnpm
          script:
            - npm install pnpm
        - name: Install dependencies
          script:
            - pnpm install
        - name: Build
          script:
            - pnpm run generate
        - name: Deploy to Halo
          imports: https://cnb.cool/puresky/secret-store/-/blob/main/puresky.yml
          script:
            - npx halo-static-pages-deploy-cli deploy -e $ENDPOINT -i $SENTENCE_COLLECTION_ID -t $PAT -f ./.output/public